services:
  # Template
  #


  db:
    image: postgres:17.4
    container_name: db
    restart: always
    environment:
      - TZ=Asia/Aqtobe
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - internal
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 1s
      timeout: 1s
      retries: 100
  

volumes:
  db_data:

networks:
  internal: