// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.0
// source: proto/doctor.proto

package genproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetDoctorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDoctorRequest) Reset() {
	*x = GetDoctorRequest{}
	mi := &file_proto_doctor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDoctorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDoctorRequest) ProtoMessage() {}

func (x *GetDoctorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_doctor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDoctorRequest.ProtoReflect.Descriptor instead.
func (*GetDoctorRequest) Descriptor() ([]byte, []int) {
	return file_proto_doctor_proto_rawDescGZIP(), []int{0}
}

func (x *GetDoctorRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type CreateDoctorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Specialty     string                 `protobuf:"bytes,2,opt,name=specialty,proto3" json:"specialty,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDoctorRequest) Reset() {
	*x = CreateDoctorRequest{}
	mi := &file_proto_doctor_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDoctorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDoctorRequest) ProtoMessage() {}

func (x *CreateDoctorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_doctor_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDoctorRequest.ProtoReflect.Descriptor instead.
func (*CreateDoctorRequest) Descriptor() ([]byte, []int) {
	return file_proto_doctor_proto_rawDescGZIP(), []int{1}
}

func (x *CreateDoctorRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateDoctorRequest) GetSpecialty() string {
	if x != nil {
		return x.Specialty
	}
	return ""
}

func (x *CreateDoctorRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type UpdateDoctorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Specialty     string                 `protobuf:"bytes,3,opt,name=specialty,proto3" json:"specialty,omitempty"`
	Email         string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDoctorRequest) Reset() {
	*x = UpdateDoctorRequest{}
	mi := &file_proto_doctor_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDoctorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDoctorRequest) ProtoMessage() {}

func (x *UpdateDoctorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_doctor_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDoctorRequest.ProtoReflect.Descriptor instead.
func (*UpdateDoctorRequest) Descriptor() ([]byte, []int) {
	return file_proto_doctor_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateDoctorRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateDoctorRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateDoctorRequest) GetSpecialty() string {
	if x != nil {
		return x.Specialty
	}
	return ""
}

func (x *UpdateDoctorRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type DeleteDoctorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDoctorRequest) Reset() {
	*x = DeleteDoctorRequest{}
	mi := &file_proto_doctor_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDoctorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDoctorRequest) ProtoMessage() {}

func (x *DeleteDoctorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_doctor_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDoctorRequest.ProtoReflect.Descriptor instead.
func (*DeleteDoctorRequest) Descriptor() ([]byte, []int) {
	return file_proto_doctor_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteDoctorRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteDoctorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDoctorResponse) Reset() {
	*x = DeleteDoctorResponse{}
	mi := &file_proto_doctor_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDoctorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDoctorResponse) ProtoMessage() {}

func (x *DeleteDoctorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_doctor_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDoctorResponse.ProtoReflect.Descriptor instead.
func (*DeleteDoctorResponse) Descriptor() ([]byte, []int) {
	return file_proto_doctor_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteDoctorResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type DoctorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Specialty     string                 `protobuf:"bytes,3,opt,name=specialty,proto3" json:"specialty,omitempty"`
	Email         string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DoctorResponse) Reset() {
	*x = DoctorResponse{}
	mi := &file_proto_doctor_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DoctorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DoctorResponse) ProtoMessage() {}

func (x *DoctorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_doctor_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DoctorResponse.ProtoReflect.Descriptor instead.
func (*DoctorResponse) Descriptor() ([]byte, []int) {
	return file_proto_doctor_proto_rawDescGZIP(), []int{5}
}

func (x *DoctorResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DoctorResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DoctorResponse) GetSpecialty() string {
	if x != nil {
		return x.Specialty
	}
	return ""
}

func (x *DoctorResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

var File_proto_doctor_proto protoreflect.FileDescriptor

const file_proto_doctor_proto_rawDesc = "" +
	"\n" +
	"\x12proto/doctor.proto\x12\x06doctor\"\"\n" +
	"\x10GetDoctorRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"]\n" +
	"\x13CreateDoctorRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1c\n" +
	"\tspecialty\x18\x02 \x01(\tR\tspecialty\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\"m\n" +
	"\x13UpdateDoctorRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1c\n" +
	"\tspecialty\x18\x03 \x01(\tR\tspecialty\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\"%\n" +
	"\x13DeleteDoctorRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\".\n" +
	"\x14DeleteDoctorResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"h\n" +
	"\x0eDoctorResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1c\n" +
	"\tspecialty\x18\x03 \x01(\tR\tspecialty\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email2\xa7\x02\n" +
	"\rDoctorService\x12A\n" +
	"\rGetDoctorByID\x12\x18.doctor.GetDoctorRequest\x1a\x16.doctor.DoctorResponse\x12C\n" +
	"\fCreateDoctor\x12\x1b.doctor.CreateDoctorRequest\x1a\x16.doctor.DoctorResponse\x12C\n" +
	"\fUpdateDoctor\x12\x1b.doctor.UpdateDoctorRequest\x1a\x16.doctor.DoctorResponse\x12I\n" +
	"\fDeleteDoctor\x12\x1b.doctor.DeleteDoctorRequest\x1a\x1c.doctor.DeleteDoctorResponseB\x1aZ\x18doctor/genproto;genprotob\x06proto3"

var (
	file_proto_doctor_proto_rawDescOnce sync.Once
	file_proto_doctor_proto_rawDescData []byte
)

func file_proto_doctor_proto_rawDescGZIP() []byte {
	file_proto_doctor_proto_rawDescOnce.Do(func() {
		file_proto_doctor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_doctor_proto_rawDesc), len(file_proto_doctor_proto_rawDesc)))
	})
	return file_proto_doctor_proto_rawDescData
}

var file_proto_doctor_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_doctor_proto_goTypes = []any{
	(*GetDoctorRequest)(nil),     // 0: doctor.GetDoctorRequest
	(*CreateDoctorRequest)(nil),  // 1: doctor.CreateDoctorRequest
	(*UpdateDoctorRequest)(nil),  // 2: doctor.UpdateDoctorRequest
	(*DeleteDoctorRequest)(nil),  // 3: doctor.DeleteDoctorRequest
	(*DeleteDoctorResponse)(nil), // 4: doctor.DeleteDoctorResponse
	(*DoctorResponse)(nil),       // 5: doctor.DoctorResponse
}
var file_proto_doctor_proto_depIdxs = []int32{
	0, // 0: doctor.DoctorService.GetDoctorByID:input_type -> doctor.GetDoctorRequest
	1, // 1: doctor.DoctorService.CreateDoctor:input_type -> doctor.CreateDoctorRequest
	2, // 2: doctor.DoctorService.UpdateDoctor:input_type -> doctor.UpdateDoctorRequest
	3, // 3: doctor.DoctorService.DeleteDoctor:input_type -> doctor.DeleteDoctorRequest
	5, // 4: doctor.DoctorService.GetDoctorByID:output_type -> doctor.DoctorResponse
	5, // 5: doctor.DoctorService.CreateDoctor:output_type -> doctor.DoctorResponse
	5, // 6: doctor.DoctorService.UpdateDoctor:output_type -> doctor.DoctorResponse
	4, // 7: doctor.DoctorService.DeleteDoctor:output_type -> doctor.DeleteDoctorResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_doctor_proto_init() }
func file_proto_doctor_proto_init() {
	if File_proto_doctor_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_doctor_proto_rawDesc), len(file_proto_doctor_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_doctor_proto_goTypes,
		DependencyIndexes: file_proto_doctor_proto_depIdxs,
		MessageInfos:      file_proto_doctor_proto_msgTypes,
	}.Build()
	File_proto_doctor_proto = out.File
	file_proto_doctor_proto_goTypes = nil
	file_proto_doctor_proto_depIdxs = nil
}
